### ISSUE TITLE
bug/enhancement

### ISSUE THREAD

**Issue by nathanapples** [djdembeck/bragibooks#279]
I think that bragibooks is tagging the narrator as an author when it should be composer or the like. If this is intentional I think it should be a setting.

**Comment by djdembeck** [comment]
Yes, the narrator will be placed as the artist, and the author as the album artist. This was adopted because it's the consensus on tagging by the audiobook community and metadata communitites.

This will show the narrator as the track artist in audiobook apps, while showing the author as the album artist.

**Comment by nathanapples** [comment]
Maybe this is the standard for Plex listening but if you listen on any audiobook listening app that can correctly display metadata like Audiobookshelf, prologue, these apps pull the narrator from the composer field not the artist field.
